stages:
  - static_analysis
  - test
  - qa_build_validation
  - qa_build

lint:
  stage: static_analysis
  script:
    make lint
  artifacts:
    paths:
      - lint-report
    expire_in: 1 week
  only:
    - merge_request
  tags:
    - ios

unit_tests:
  stage: test
  script:
    - make test
  artifacts:
    paths:
      - TestResults.xcresult
      - test-coverage-report.txt
    expire_in: 1 week
  only:
    - merge_request
  tags:
    - ios

qa_build_validation:
  stage: qa_build_validation
  script:
    make qa_build_validation
  only:
    - merge_request
  tags:
    - ios

qa_build_upload:
  stage: qa_build
  script:
    make qa_build_publish
  artifacts:
    paths: 
    - Passbolt.ipa
    expire_in: 1 week
  only:
    - develop
    - /^release.*$/
  tags:
    - ios
