reporter: "xcode"

only_rules:
  - array_init
  - balanced_xctest_lifecycle
  - block_based_kvo
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - contains_over_filter_count 
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - deployment_target
  - discouraged_assert
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - fallthrough
  - fatal_error_message
  - file_length
  - file_name_no_space
  # In swiftlint 0.43.1 does not implement it properly, disabling until fixed
  # - file_types_order
  - first_where 
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - ibinspectable_in_extension
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - last_where
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - nsobject_prefer_isequal
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - orphaned_doc_comment
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_interface_builder
  - protocol_property_accessors_order
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_set_access_control
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - superfluous_disable_command
  - switch_case_alignment
  - switch_case_on_newline
  - todo
  - toggle_bool
  - trailing_comma
  - trailing_semicolon
  - trailing_whitespace
  # In swiftlint 0.43.1 does not implement it properly, disabling until fixed
  # - type_contents_order
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - void_return
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

closure_body_length:
  warning: 50
  
cyclomatic_complexity:
  warning: 10
  error: 32
  
file_length:
  warning: 500

# In swiftlint 0.43.1 does not implement it properly, disabling until fixed
# file_types_order:
#   order:
#      - SwiftLintFramework.FileType.supportingType
#      - SwiftLintFramework.FileType.mainType
#      - SwiftLintFramework.FileType.extension
#      - SwiftLintFramework.FileType.previewProvider
     
function_body_length:
  warning: 100
  error: 300

ibinspectable_in_extension:
  error
  
identifier_name:
  min_length: 2
  max_length: 50
  
indentation_width:
  indentation_width: 2
  
line_length:
  warning: 120
  ignores_comments: true

trailing_whitespace:
  ignores_empty_lines: true
  
type_name:
  min_length: 3
  max_length: 50
  excluded:
    - UI
    - ID
     
# In swiftlint 0.43.1 does not implement it properly, disabling until fixed
# type_contents_order:
#   order:
#      - SwiftLintFramework.TypeContent.typeAlias
#      - SwiftLintFramework.TypeContent.associatedType
#      - SwiftLintFramework.TypeContent.subtype
#      - SwiftLintFramework.TypeContent.case
#      - SwiftLintFramework.TypeContent.typeProperty
#      - SwiftLintFramework.TypeContent.typeMethod
#      - SwiftLintFramework.TypeContent.ibInspectable
#      - SwiftLintFramework.TypeContent.ibOutlet
#      - SwiftLintFramework.TypeContent.instanceProperty
#      - SwiftLintFramework.TypeContent.initializer
#      - SwiftLintFramework.TypeContent.deinitializer
#      - SwiftLintFramework.TypeContent.subscript
#      - SwiftLintFramework.TypeContent.viewLifeCycleMethod
#      - SwiftLintFramework.TypeContent.ibAction
#      - SwiftLintFramework.TypeContent.otherMethod

excluded:
  - .build
  - "*/DerivedData/"
  - "./DerivedData"
  - "*/Package.swift"
  - "*Tests.swift"
